# Built from Dockerfile.development
# To rebuild:
# docker build --file development/Dockerfile.development -t acmilabs/playlistlabel-development:v1 .
# docker push acmilabs/playlistlabel-development:v1
FROM acmilabs/playlistlabel-development:v1

COPY . /code/
WORKDIR /code/
