// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * * `No access` - No access
 * * `View onsite` - View onsite
 * * `View anywhere` - View anywhere
 */
export type AccessLevelEnum = 'No access' | 'View onsite' | 'View anywhere';

/**
 * Schema-only serializer documenting an item returned by build_caption_tracks().
 */
export type CaptionTrack = {
    id: number | string;
    locale: string;
    label: string;
    url: string;
    format: FormatEnum;
    alternate_urls: CaptionTrackAlternateUrls;
    is_default: boolean;
};

/**
 * Schema-only serializer documenting the alternate subtitle formats of a caption track.
 */
export type CaptionTrackAlternateUrls = {
    vtt?: string;
    srt?: string;
};

/**
 * Serialise the collectible content, for use in /lenses/<code>/taps/
 */
export type Collectible = {
    readonly id: number;
    title: string;
    /**
     * Title (Simplified Chinese)
     *
     * The title of this collectible. e.g. Film cameras.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    title_zh_hans?: string;
    /**
     * Title (Punjabi)
     *
     * The title of this collectible. e.g. Film cameras.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    title_pa?: string;
    /**
     * Title (Hindi)
     *
     * The title of this collectible. e.g. Film cameras.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    title_hi?: string;
    /**
     * Subtitles (Simplified Chinese)
     *
     * Smaller text that appears below the title.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    subtitles_zh_hans?: string;
    /**
     * Subtitles (Punjabi)
     *
     * Smaller text that appears below the title.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    subtitles_pa?: string;
    /**
     * Subtitles (Hindi)
     *
     * Smaller text that appears below the title.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    subtitles_hi?: string;
    /**
     * Collectible type (Simplified Chinese)
     *
     * The type of this collectible, shown on the post-visit website. Defaults to the type of a related work.
     */
    collectible_type_zh_hans?: string;
    /**
     * Collectible type (Punjabi)
     *
     * The type of this collectible, shown on the post-visit website. Defaults to the type of a related work.
     */
    collectible_type_pa?: string;
    /**
     * Collectible type (Hindi)
     *
     * The type of this collectible, shown on the post-visit website. Defaults to the type of a related work.
     */
    collectible_type_hi?: string;
    type: string;
    subtitles: string;
    readonly columns: Array<LabelColumn>;
    work: WorkLink;
    readonly images: Array<WorkImage>;
    /**
     * Visitors will be taken to this URL instead of a standard work/s view
     */
    url_override?: string | string;
    /**
     * Check this box to mark this collectible as an Event, like a film or education workshop.
     */
    is_an_event?: boolean;
};

/**
 * A constellation serializer containing only data needed to render a link to a constellation
 */
export type ConstellationInList = {
    readonly id: number;
    /**
     * Constellation title
     *
     * For internal use. This appears in XOS constellation preview.
     */
    name: string;
    /**
     * Constellation description
     *
     * For internal use. Keep this short and sweet.
     */
    description?: string;
};

/**
 * A serializer for the ExternalReference object.
 */
export type ExternalReference = {
    readonly id: number;
    source: Source;
    /**
     * The ID of the record that this information was imported from. e.g. Q375590
     */
    source_identifier?: string | null;
};

/**
 * * `vtt` - vtt
 * * `srt` - srt
 */
export type FormatEnum = 'vtt' | 'srt';

/**
 * Schema-only serializer documenting an item returned by Label.columns().
 */
export type LabelColumn = {
    content: string;
    style: StyleEnum;
};

/**
 * A serializer for the Part object.
 */
export type Part = {
    /**
     * The name of the part. E.g. Lid or Base
     */
    name: string;
    /**
     * The id of the part relative to the work. E.g. Part 1 or Part 2
     */
    identifier?: string;
    /**
     * A description of the part
     */
    description?: string;
};

/**
 * Serializes minimal fields from Place
 */
export type Place = {
    readonly id: number;
    name: string;
    slug: string;
};

export type Playlist = {
    readonly id: number;
    /**
     * Title of the playlist.
     */
    title: string;
    /**
     * Heading to introduce the playlist on labels that allow it.
     */
    introduction_title?: string;
    readonly introduction_content: string;
    readonly playlist_labels: Array<PlaylistLabel>;
    /**
     * Main background image used for the interactive label interface.
     */
    background?: string | null;
    /**
     * The [width, height] of the background image in pixels.
     */
    readonly background_dimensions: [
        number,
        number
    ] | null;
};

export type PlaylistCollectible = {
    label: Collectible;
    video: Video;
    readonly resource: string | null;
    readonly subtitles: string | null;
    /**
     * SVG data used as the clickable target region in the interactive label interface.
     */
    region_svg?: string | null;
};

/**
 * Schema-only serializer documenting the placeholder item returned for a Playlist with no labels.
 */
export type PlaylistEmptyItem = {
    readonly label: unknown;
    /**
     * A static "playlist empty" video.
     */
    resource: string;
    /**
     * Subtitles containing debug information for the empty Playlist.
     */
    subtitles: string;
    readonly region_svg: unknown;
};

export type PlaylistLabel = PlaylistCollectible | PlaylistEmptyItem;

/**
 * Serializes minimal fields from ProductionDate
 */
export type ProductionDate = {
    /**
     * The production date of the work. e.g. 2018
     */
    date: string;
    /**
     * Notes on the production date
     */
    notes?: string;
    to_year: number | string;
};

/**
 * * `work` - work
 * * `group` - group
 */
export type RecordTypeEnum = 'work' | 'group';

/**
 * Serializes minimal fields from Creator
 */
export type RoleInWork = {
    readonly id: number;
    name: string;
    creator_id: number;
    /**
     * Get the Creator's Wikidata ID from an external reference.
     */
    readonly creator_wikidata_id: string | null;
    role: string;
    role_id: number;
    is_primary?: boolean;
};

/**
 * A serializer for the Source object.
 */
export type Source = {
    name: string;
    slug: string;
};

/**
 * * `standard` - standard
 * * `smaller` - smaller
 */
export type StyleEnum = 'standard' | 'smaller';

/**
 * A serializer for the UserRecommendation object.
 */
export type UserRecommendation = {
    /**
     * Get the user's display name. If the user has set a first and last name, show that.
     * Otherwise show the user's username.
     */
    readonly display_name: string;
    readonly job_title: string;
    readonly avatar_image: string | null;
    /**
     * Why you are recommending this work
     *
     * 40 word limit. This appears on the constellation table when a visitor selects a work.
     */
    quote?: string;
};

/**
 * A serializer for the Video objecte.
 */
export type Video = {
    readonly id: number;
    /**
     * A searchable title for the asset.
     */
    title: string;
    readonly resource: string;
    readonly web_resource: string;
    readonly duration_secs: number | null;
    /**
     * The subtitles file. e.g. andy.srt
     */
    subtitles?: string | null;
    /**
     * The vtt subtitles file for html video players. e.g. andy.vtt
     */
    subtitles_vtt?: string | null;
    readonly caption_tracks: Array<CaptionTrack>;
    master_metadata?: unknown;
    access_metadata?: unknown;
    web_metadata?: unknown;
    /**
     * The access level of this object. e.g. No access, onsite or anywhere
     *
     * * `No access` - No access
     * * `View onsite` - View onsite
     * * `View anywhere` - View anywhere
     */
    access_level?: AccessLevelEnum;
    readonly snapshot: string;
    readonly animated_snapshot: string;
    /**
     * A transcription of the video using OpenAI Whisper
     */
    transcription?: unknown;
    /**
     * Predictions of the actions and objects that appear in frames of this video using Huggingface and YOLO
     */
    classification?: unknown;
    /**
     * The most common words in the transcription as [word, count] pairs.
     */
    readonly tags: Array<[
        string | number,
        string | number
    ]> | null;
    readonly works: Array<VideoWork>;
};

/**
 * A serializer for the Video object.
 */
export type VideoLink = {
    readonly id: number;
    name?: string;
    /**
     * A link to a video. e.g. https://youtu.be/dQw4w9WgXcQ
     */
    uri?: string | string;
};

/**
 * A serialiser for minimal Video Work objects.
 */
export type VideoWork = {
    readonly id: number;
    /**
     * Imported title
     *
     * The title of the work for the public.
     */
    readonly title: string;
    /**
     * A url-friendly version of the title
     */
    slug: string;
};

/**
 * A serializer for Work objects.
 */
export type Work = {
    readonly id: number;
    /**
     * Identifier indicating import source. e.g. 'xos-3456', 'tmdb-movie-2512'
     */
    readonly acmi_id: string | null;
    title: string;
    /**
     * Imported title (Simplified Chinese)
     *
     * The title of the work for the public.
     */
    title_zh_hans?: string;
    /**
     * Imported title (Punjabi)
     *
     * The title of the work for the public.
     */
    title_pa?: string;
    /**
     * Imported title (Hindi)
     *
     * The title of the work for the public.
     */
    title_hi?: string;
    /**
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation?: string;
    /**
     * Title annotation (Simplified Chinese)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_zh_hans?: string;
    /**
     * Title annotation (Punjabi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_pa?: string;
    /**
     * Title annotation (Hindi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_hi?: string;
    /**
     * A url-friendly version of the title
     */
    slug: string;
    /**
     * Return a comma-separated list of primary creators.
     */
    readonly creator_credit: string;
    credit_line: string;
    /**
     * Imported credit line (Simplified Chinese)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_zh_hans?: string;
    /**
     * Imported credit line (Punjabi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_pa?: string;
    /**
     * Imported credit line (Hindi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_hi?: string;
    /**
     * Return the headline credit based on production year and places.
     */
    readonly headline_credit: string;
    thumbnail: WorkThumbnail | null;
    readonly video_links: Array<VideoLink>;
    record_type?: RecordTypeEnum;
    /**
     * We want works without a work_type to default to type 'Film' on the API.
     */
    readonly type: string;
    /**
     * Is this work currently on display in an exhibition?
     */
    is_on_display?: boolean;
    /**
     * The last place this work was on display
     */
    last_on_display_place?: string | null;
    /**
     * The date when this work was last on display
     */
    last_on_display_date?: string | null;
    /**
     * Indigenous context?
     *
     * Checking this will visually decorate the label and online work to indicate an indigenous context.
     */
    is_context_indigenous?: boolean;
    /**
     * A description of the materials used in this work
     */
    material_description?: string;
    /**
     * Unpublish this Work from XOS and the XOS API.
     */
    unpublished?: boolean;
    /**
     * Checks if the external_override field is set or returns the value of external.
     * There is also an `external` API query filter in WorkViewSet.
     */
    readonly external: boolean;
    /**
     * The first production date of this work
     */
    readonly first_production_date: string | null;
    /**
     * Whether this work was commissioned by ACMI.
     */
    readonly commissioned: boolean;
    /**
     * Whether this work is in the public domain.
     */
    readonly public_domain: boolean;
    readonly external_references: Array<ExternalReference>;
    brief_description: string;
    readonly constellations_primary: Array<ConstellationInList>;
    readonly constellations_other: Array<ConstellationInList>;
    readonly recommendations: Array<UserRecommendation>;
    creator_credit_for_label: string;
    /**
     * Creator credit for label (Simplified Chinese)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_zh_hans?: string;
    /**
     * Creator credit for label (Punjabi)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_pa?: string;
    /**
     * Creator credit for label (Hindi)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_hi?: string;
    headline_credit_for_label: string;
    /**
     * Headline credit for label (Simplified Chinese)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_zh_hans?: string;
    /**
     * Headline credit for label (Punjabi)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_pa?: string;
    /**
     * Headline credit for label (Hindi)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_hi?: string;
    /**
     * Imported title for label (Simplified Chinese)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_zh_hans?: string;
    /**
     * Imported title for label (Punjabi)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_pa?: string;
    /**
     * Imported title for label (Hindi)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_hi?: string;
    /**
     * Title for label override (Simplified Chinese)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_zh_hans?: string;
    /**
     * Title for label override (Punjabi)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_pa?: string;
    /**
     * Title for label override (Hindi)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_hi?: string;
    /**
     * Imported description for label (Simplified Chinese)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_zh_hans?: string;
    /**
     * Imported description for label (Punjabi)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_pa?: string;
    /**
     * Imported description for label (Hindi)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_hi?: string;
    /**
     * Description for label override (Simplified Chinese)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_zh_hans?: string;
    /**
     * Description for label override (Punjabi)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_pa?: string;
    /**
     * Description for label override (Hindi)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_hi?: string;
    /**
     * Imported description (Simplified Chinese)
     *
     * The brief description of the work for the public.
     */
    description_zh_hans?: string;
    /**
     * Imported description (Punjabi)
     *
     * The brief description of the work for the public.
     */
    description_pa?: string;
    /**
     * Imported description (Hindi)
     *
     * The brief description of the work for the public.
     */
    description_hi?: string;
    /**
     * Description override (Simplified Chinese)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_zh_hans?: string;
    /**
     * Description override (Punjabi)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_pa?: string;
    /**
     * Description override (Hindi)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_hi?: string;
    title_for_label: string;
    description: string;
    description_for_label: Array<unknown>;
    credit_line_for_label: string;
    readonly details: Array<WorkDetail>;
    stats: WorkStats;
    readonly links: Array<WorkLinkItem>;
    readonly creators_primary: Array<RoleInWork>;
    readonly creators_other: Array<RoleInWork>;
    /**
     * Return the a media note if no images or videos are attached to this work.
     */
    readonly media_note: string | null;
    readonly images: Array<WorkImage>;
    readonly videos: Array<Video>;
    readonly holdings: Array<Part>;
    part_of: WorkSubLink;
    readonly parts: Array<WorkSubLink>;
    readonly part_siblings: Array<WorkSubLink>;
    group: WorkSubLink;
    readonly group_works: Array<WorkSubLink>;
    readonly group_siblings: Array<WorkSubLink>;
    source: Source;
    /**
     * The ID of the record that this information was imported from. e.g. B2000606
     */
    source_identifier?: string | null;
    /**
     * The EaaSI game emulator environment ID for this work.
     */
    eaas_environment_id?: string | null;
    readonly production_places: Array<Place>;
    readonly production_dates: Array<ProductionDate>;
    labels: Array<number>;
    /**
     * Title override (Simplified Chinese)
     *
     * Text that overrides the Work's title. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.
     */
    title_override_zh_hans?: string;
    /**
     * Title override (Punjabi)
     *
     * Text that overrides the Work's title. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.
     */
    title_override_pa?: string;
    /**
     * Title override (Hindi)
     *
     * Text that overrides the Work's title. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.
     */
    title_override_hi?: string;
    /**
     * Imported credit line for label (Simplified Chinese)
     *
     * An alternative credit line for labels.
     */
    credit_line_for_label_zh_hans?: string;
    /**
     * Imported credit line for label (Punjabi)
     *
     * An alternative credit line for labels.
     */
    credit_line_for_label_pa?: string;
    /**
     * Imported credit line for label (Hindi)
     *
     * An alternative credit line for labels.
     */
    credit_line_for_label_hi?: string;
    /**
     * Credit line for label override (Simplified Chinese)
     *
     * Override the credit line for labels.
     */
    credit_line_for_label_override_zh_hans?: string;
    /**
     * Credit line for label override (Punjabi)
     *
     * Override the credit line for labels.
     */
    credit_line_for_label_override_pa?: string;
    /**
     * Credit line for label override (Hindi)
     *
     * Override the credit line for labels.
     */
    credit_line_for_label_override_hi?: string;
    /**
     * Credit line override (Simplified Chinese)
     *
     * Text that overrides the Work's credit line.
     */
    credit_line_override_zh_hans?: string;
    /**
     * Credit line override (Punjabi)
     *
     * Text that overrides the Work's credit line.
     */
    credit_line_override_pa?: string;
    /**
     * Credit line override (Hindi)
     *
     * Text that overrides the Work's credit line.
     */
    credit_line_override_hi?: string;
};

/**
 * Schema-only serializer documenting an item in the Work `details` list.
 */
export type WorkDetail = {
    label: string;
    display_values: Array<string>;
    /**
     * Underlying values for the detail, the shape varies by detail.
     */
    values?: Array<unknown>;
};

/**
 * A serializer for Work Images.
 */
export type WorkImage = {
    readonly id: number;
    image_file: string;
    image_file_thumbnail?: string | null;
    image_file_xs?: string | null;
    image_file_s?: string | null;
    image_file_m?: string | null;
    image_file_l?: string | null;
    caption?: string;
    credit_line?: string;
    /**
     * The alternative text for the image. See <a href="https://acmikb.atlassian.net/wiki/spaces/OPS/pages/7964025/" target="_blank">this guide</a> for writing alt text.
     */
    alt_text?: string;
    width?: number | null;
    height?: number | null;
    /**
     * The access level of this object. e.g. No access, onsite or anywhere
     *
     * * `No access` - No access
     * * `View onsite` - View onsite
     * * `View anywhere` - View anywhere
     */
    access_level?: AccessLevelEnum;
};

/**
 * A serializer for Work objects that contains the info needed to represent
 * the work in a constellation, or a tap list.
 */
export type WorkLink = {
    readonly id: number;
    /**
     * Identifier indicating import source. e.g. 'xos-3456', 'tmdb-movie-2512'
     */
    readonly acmi_id: string | null;
    title: string;
    /**
     * Imported title (Simplified Chinese)
     *
     * The title of the work for the public.
     */
    title_zh_hans?: string;
    /**
     * Imported title (Punjabi)
     *
     * The title of the work for the public.
     */
    title_pa?: string;
    /**
     * Imported title (Hindi)
     *
     * The title of the work for the public.
     */
    title_hi?: string;
    /**
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation?: string;
    /**
     * Title annotation (Simplified Chinese)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_zh_hans?: string;
    /**
     * Title annotation (Punjabi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_pa?: string;
    /**
     * Title annotation (Hindi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_hi?: string;
    /**
     * A url-friendly version of the title
     */
    slug: string;
    /**
     * Return a comma-separated list of primary creators.
     */
    readonly creator_credit: string;
    credit_line: string;
    /**
     * Imported credit line (Simplified Chinese)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_zh_hans?: string;
    /**
     * Imported credit line (Punjabi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_pa?: string;
    /**
     * Imported credit line (Hindi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_hi?: string;
    /**
     * Return the headline credit based on production year and places.
     */
    readonly headline_credit: string;
    thumbnail: WorkThumbnail | null;
    readonly video_links: Array<VideoLink>;
    record_type?: RecordTypeEnum;
    /**
     * We want works without a work_type to default to type 'Film' on the API.
     */
    readonly type: string;
    /**
     * Is this work currently on display in an exhibition?
     */
    is_on_display?: boolean;
    /**
     * The last place this work was on display
     */
    last_on_display_place?: string | null;
    /**
     * The date when this work was last on display
     */
    last_on_display_date?: string | null;
    /**
     * Indigenous context?
     *
     * Checking this will visually decorate the label and online work to indicate an indigenous context.
     */
    is_context_indigenous?: boolean;
    /**
     * A description of the materials used in this work
     */
    material_description?: string;
    /**
     * Unpublish this Work from XOS and the XOS API.
     */
    unpublished?: boolean;
    /**
     * Checks if the external_override field is set or returns the value of external.
     * There is also an `external` API query filter in WorkViewSet.
     */
    readonly external: boolean;
    /**
     * The first production date of this work
     */
    readonly first_production_date: string | null;
    /**
     * Whether this work was commissioned by ACMI.
     */
    readonly commissioned: boolean;
    /**
     * Whether this work is in the public domain.
     */
    readonly public_domain: boolean;
    readonly external_references: Array<ExternalReference>;
    brief_description: string;
    readonly constellations_primary: Array<ConstellationInList>;
    readonly constellations_other: Array<ConstellationInList>;
    readonly recommendations: Array<UserRecommendation>;
    creator_credit_for_label: string;
    /**
     * Creator credit for label (Simplified Chinese)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_zh_hans?: string;
    /**
     * Creator credit for label (Punjabi)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_pa?: string;
    /**
     * Creator credit for label (Hindi)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_hi?: string;
    headline_credit_for_label: string;
    /**
     * Headline credit for label (Simplified Chinese)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_zh_hans?: string;
    /**
     * Headline credit for label (Punjabi)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_pa?: string;
    /**
     * Headline credit for label (Hindi)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_hi?: string;
    /**
     * Imported title for label (Simplified Chinese)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_zh_hans?: string;
    /**
     * Imported title for label (Punjabi)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_pa?: string;
    /**
     * Imported title for label (Hindi)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_hi?: string;
    /**
     * Title for label override (Simplified Chinese)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_zh_hans?: string;
    /**
     * Title for label override (Punjabi)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_pa?: string;
    /**
     * Title for label override (Hindi)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_hi?: string;
    /**
     * Imported description for label (Simplified Chinese)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_zh_hans?: string;
    /**
     * Imported description for label (Punjabi)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_pa?: string;
    /**
     * Imported description for label (Hindi)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_hi?: string;
    /**
     * Description for label override (Simplified Chinese)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_zh_hans?: string;
    /**
     * Description for label override (Punjabi)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_pa?: string;
    /**
     * Description for label override (Hindi)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_hi?: string;
    /**
     * Imported description (Simplified Chinese)
     *
     * The brief description of the work for the public.
     */
    description_zh_hans?: string;
    /**
     * Imported description (Punjabi)
     *
     * The brief description of the work for the public.
     */
    description_pa?: string;
    /**
     * Imported description (Hindi)
     *
     * The brief description of the work for the public.
     */
    description_hi?: string;
    /**
     * Description override (Simplified Chinese)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_zh_hans?: string;
    /**
     * Description override (Punjabi)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_pa?: string;
    /**
     * Description override (Hindi)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_hi?: string;
};

/**
 * Schema-only serializer documenting an item in the Work `links` list.
 */
export type WorkLinkItem = {
    url: string;
    title: string;
    source: string;
};

/**
 * Schema-only serializer documenting the Work `stats` field.
 */
export type WorkStats = {
    tap_count: number;
};

/**
 * A serializer for Work objects that contains the info needed to represent
 * the work from another work.
 */
export type WorkSubLink = {
    readonly id: number;
    /**
     * Identifier indicating import source. e.g. 'xos-3456', 'tmdb-movie-2512'
     */
    readonly acmi_id: string | null;
    title: string;
    /**
     * Imported title (Simplified Chinese)
     *
     * The title of the work for the public.
     */
    title_zh_hans?: string;
    /**
     * Imported title (Punjabi)
     *
     * The title of the work for the public.
     */
    title_pa?: string;
    /**
     * Imported title (Hindi)
     *
     * The title of the work for the public.
     */
    title_hi?: string;
    /**
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation?: string;
    /**
     * Title annotation (Simplified Chinese)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_zh_hans?: string;
    /**
     * Title annotation (Punjabi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_pa?: string;
    /**
     * Title annotation (Hindi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_hi?: string;
    /**
     * A url-friendly version of the title
     */
    slug: string;
    /**
     * Return a comma-separated list of primary creators.
     */
    readonly creator_credit: string;
    credit_line: string;
    /**
     * Imported credit line (Simplified Chinese)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_zh_hans?: string;
    /**
     * Imported credit line (Punjabi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_pa?: string;
    /**
     * Imported credit line (Hindi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_hi?: string;
    /**
     * Return the headline credit based on production year and places.
     */
    readonly headline_credit: string;
    thumbnail: WorkThumbnail | null;
    readonly video_links: Array<VideoLink>;
    record_type?: RecordTypeEnum;
    /**
     * We want works without a work_type to default to type 'Film' on the API.
     */
    readonly type: string;
    /**
     * Is this work currently on display in an exhibition?
     */
    is_on_display?: boolean;
    /**
     * The last place this work was on display
     */
    last_on_display_place?: string | null;
    /**
     * The date when this work was last on display
     */
    last_on_display_date?: string | null;
    /**
     * Indigenous context?
     *
     * Checking this will visually decorate the label and online work to indicate an indigenous context.
     */
    is_context_indigenous?: boolean;
    /**
     * A description of the materials used in this work
     */
    material_description?: string;
    /**
     * Unpublish this Work from XOS and the XOS API.
     */
    unpublished?: boolean;
    /**
     * Checks if the external_override field is set or returns the value of external.
     * There is also an `external` API query filter in WorkViewSet.
     */
    readonly external: boolean;
    /**
     * The first production date of this work
     */
    readonly first_production_date: string | null;
    /**
     * Whether this work was commissioned by ACMI.
     */
    readonly commissioned: boolean;
    /**
     * Whether this work is in the public domain.
     */
    readonly public_domain: boolean;
    readonly external_references: Array<ExternalReference>;
};

/**
 * Schema-only serializer documenting the shape returned by Work.thumbnail().
 */
export type WorkThumbnail = {
    image_url: string;
    animated_image_url?: string | string;
    has_video: boolean;
};

/**
 * Schema-only serializer documenting an item returned by build_caption_tracks().
 */
export type CaptionTrackWritable = {
    locale: string;
    label: string;
    url: string;
    format: FormatEnum;
    alternate_urls: CaptionTrackAlternateUrls;
    is_default: boolean;
};

/**
 * Serialise the collectible content, for use in /lenses/<code>/taps/
 */
export type CollectibleWritable = {
    title: string;
    /**
     * Title (Simplified Chinese)
     *
     * The title of this collectible. e.g. Film cameras.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    title_zh_hans?: string;
    /**
     * Title (Punjabi)
     *
     * The title of this collectible. e.g. Film cameras.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    title_pa?: string;
    /**
     * Title (Hindi)
     *
     * The title of this collectible. e.g. Film cameras.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    title_hi?: string;
    /**
     * Subtitles (Simplified Chinese)
     *
     * Smaller text that appears below the title.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    subtitles_zh_hans?: string;
    /**
     * Subtitles (Punjabi)
     *
     * Smaller text that appears below the title.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    subtitles_pa?: string;
    /**
     * Subtitles (Hindi)
     *
     * Smaller text that appears below the title.<br/>Use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> to format
     */
    subtitles_hi?: string;
    /**
     * Collectible type (Simplified Chinese)
     *
     * The type of this collectible, shown on the post-visit website. Defaults to the type of a related work.
     */
    collectible_type_zh_hans?: string;
    /**
     * Collectible type (Punjabi)
     *
     * The type of this collectible, shown on the post-visit website. Defaults to the type of a related work.
     */
    collectible_type_pa?: string;
    /**
     * Collectible type (Hindi)
     *
     * The type of this collectible, shown on the post-visit website. Defaults to the type of a related work.
     */
    collectible_type_hi?: string;
    type: string;
    subtitles: string;
    /**
     * Visitors will be taken to this URL instead of a standard work/s view
     */
    url_override?: string | string;
    /**
     * Check this box to mark this collectible as an Event, like a film or education workshop.
     */
    is_an_event?: boolean;
};

/**
 * A constellation serializer containing only data needed to render a link to a constellation
 */
export type ConstellationInListWritable = {
    /**
     * Constellation title
     *
     * For internal use. This appears in XOS constellation preview.
     */
    name: string;
    /**
     * Constellation description
     *
     * For internal use. Keep this short and sweet.
     */
    description?: string;
};

/**
 * A serializer for the ExternalReference object.
 */
export type ExternalReferenceWritable = {
    /**
     * The ID of the record that this information was imported from. e.g. Q375590
     */
    source_identifier?: string | null;
};

/**
 * Serializes minimal fields from Place
 */
export type PlaceWritable = {
    name: string;
    slug: string;
};

export type PlaylistWritable = {
    /**
     * Title of the playlist.
     */
    title: string;
    /**
     * Heading to introduce the playlist on labels that allow it.
     */
    introduction_title?: string;
    /**
     * Main background image used for the interactive label interface.
     */
    background?: string | null;
};

export type PlaylistCollectibleWritable = {
    /**
     * SVG data used as the clickable target region in the interactive label interface.
     */
    region_svg?: string | null;
};

/**
 * Schema-only serializer documenting the placeholder item returned for a Playlist with no labels.
 */
export type PlaylistEmptyItemWritable = {
    /**
     * A static "playlist empty" video.
     */
    resource: string;
    /**
     * Subtitles containing debug information for the empty Playlist.
     */
    subtitles: string;
};

export type PlaylistLabelWritable = PlaylistCollectibleWritable | PlaylistEmptyItemWritable;

/**
 * Serializes minimal fields from ProductionDate
 */
export type ProductionDateWritable = {
    /**
     * The production date of the work. e.g. 2018
     */
    date: string;
    /**
     * Notes on the production date
     */
    notes?: string;
};

/**
 * Serializes minimal fields from Creator
 */
export type RoleInWorkWritable = {
    name: string;
    creator_id: number;
    role: string;
    role_id: number;
    is_primary?: boolean;
};

/**
 * A serializer for the UserRecommendation object.
 */
export type UserRecommendationWritable = {
    /**
     * Why you are recommending this work
     *
     * 40 word limit. This appears on the constellation table when a visitor selects a work.
     */
    quote?: string;
};

/**
 * A serializer for the Video objecte.
 */
export type VideoWritable = {
    /**
     * A searchable title for the asset.
     */
    title: string;
    /**
     * The subtitles file. e.g. andy.srt
     */
    subtitles?: string | null;
    /**
     * The vtt subtitles file for html video players. e.g. andy.vtt
     */
    subtitles_vtt?: string | null;
    master_metadata?: unknown;
    access_metadata?: unknown;
    web_metadata?: unknown;
    /**
     * The access level of this object. e.g. No access, onsite or anywhere
     *
     * * `No access` - No access
     * * `View onsite` - View onsite
     * * `View anywhere` - View anywhere
     */
    access_level?: AccessLevelEnum;
    /**
     * A transcription of the video using OpenAI Whisper
     */
    transcription?: unknown;
    /**
     * Predictions of the actions and objects that appear in frames of this video using Huggingface and YOLO
     */
    classification?: unknown;
};

/**
 * A serializer for the Video object.
 */
export type VideoLinkWritable = {
    name?: string;
    /**
     * A link to a video. e.g. https://youtu.be/dQw4w9WgXcQ
     */
    uri?: string | string;
};

/**
 * A serialiser for minimal Video Work objects.
 */
export type VideoWorkWritable = {
    /**
     * A url-friendly version of the title
     */
    slug: string;
};

/**
 * A serializer for Work objects.
 */
export type WorkWritable = {
    title: string;
    /**
     * Imported title (Simplified Chinese)
     *
     * The title of the work for the public.
     */
    title_zh_hans?: string;
    /**
     * Imported title (Punjabi)
     *
     * The title of the work for the public.
     */
    title_pa?: string;
    /**
     * Imported title (Hindi)
     *
     * The title of the work for the public.
     */
    title_hi?: string;
    /**
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation?: string;
    /**
     * Title annotation (Simplified Chinese)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_zh_hans?: string;
    /**
     * Title annotation (Punjabi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_pa?: string;
    /**
     * Title annotation (Hindi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_hi?: string;
    /**
     * A url-friendly version of the title
     */
    slug: string;
    credit_line: string;
    /**
     * Imported credit line (Simplified Chinese)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_zh_hans?: string;
    /**
     * Imported credit line (Punjabi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_pa?: string;
    /**
     * Imported credit line (Hindi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_hi?: string;
    record_type?: RecordTypeEnum;
    /**
     * Is this work currently on display in an exhibition?
     */
    is_on_display?: boolean;
    /**
     * The last place this work was on display
     */
    last_on_display_place?: string | null;
    /**
     * The date when this work was last on display
     */
    last_on_display_date?: string | null;
    /**
     * Indigenous context?
     *
     * Checking this will visually decorate the label and online work to indicate an indigenous context.
     */
    is_context_indigenous?: boolean;
    /**
     * A description of the materials used in this work
     */
    material_description?: string;
    /**
     * Unpublish this Work from XOS and the XOS API.
     */
    unpublished?: boolean;
    brief_description: string;
    creator_credit_for_label: string;
    /**
     * Creator credit for label (Simplified Chinese)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_zh_hans?: string;
    /**
     * Creator credit for label (Punjabi)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_pa?: string;
    /**
     * Creator credit for label (Hindi)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_hi?: string;
    headline_credit_for_label: string;
    /**
     * Headline credit for label (Simplified Chinese)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_zh_hans?: string;
    /**
     * Headline credit for label (Punjabi)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_pa?: string;
    /**
     * Headline credit for label (Hindi)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_hi?: string;
    /**
     * Imported title for label (Simplified Chinese)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_zh_hans?: string;
    /**
     * Imported title for label (Punjabi)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_pa?: string;
    /**
     * Imported title for label (Hindi)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_hi?: string;
    /**
     * Title for label override (Simplified Chinese)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_zh_hans?: string;
    /**
     * Title for label override (Punjabi)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_pa?: string;
    /**
     * Title for label override (Hindi)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_hi?: string;
    /**
     * Imported description for label (Simplified Chinese)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_zh_hans?: string;
    /**
     * Imported description for label (Punjabi)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_pa?: string;
    /**
     * Imported description for label (Hindi)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_hi?: string;
    /**
     * Description for label override (Simplified Chinese)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_zh_hans?: string;
    /**
     * Description for label override (Punjabi)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_pa?: string;
    /**
     * Description for label override (Hindi)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_hi?: string;
    /**
     * Imported description (Simplified Chinese)
     *
     * The brief description of the work for the public.
     */
    description_zh_hans?: string;
    /**
     * Imported description (Punjabi)
     *
     * The brief description of the work for the public.
     */
    description_pa?: string;
    /**
     * Imported description (Hindi)
     *
     * The brief description of the work for the public.
     */
    description_hi?: string;
    /**
     * Description override (Simplified Chinese)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_zh_hans?: string;
    /**
     * Description override (Punjabi)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_pa?: string;
    /**
     * Description override (Hindi)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_hi?: string;
    title_for_label: string;
    description: string;
    description_for_label: Array<unknown>;
    credit_line_for_label: string;
    /**
     * The ID of the record that this information was imported from. e.g. B2000606
     */
    source_identifier?: string | null;
    /**
     * The EaaSI game emulator environment ID for this work.
     */
    eaas_environment_id?: string | null;
    labels: Array<number>;
    /**
     * Title override (Simplified Chinese)
     *
     * Text that overrides the Work's title. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.
     */
    title_override_zh_hans?: string;
    /**
     * Title override (Punjabi)
     *
     * Text that overrides the Work's title. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.
     */
    title_override_pa?: string;
    /**
     * Title override (Hindi)
     *
     * Text that overrides the Work's title. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.
     */
    title_override_hi?: string;
    /**
     * Imported credit line for label (Simplified Chinese)
     *
     * An alternative credit line for labels.
     */
    credit_line_for_label_zh_hans?: string;
    /**
     * Imported credit line for label (Punjabi)
     *
     * An alternative credit line for labels.
     */
    credit_line_for_label_pa?: string;
    /**
     * Imported credit line for label (Hindi)
     *
     * An alternative credit line for labels.
     */
    credit_line_for_label_hi?: string;
    /**
     * Credit line for label override (Simplified Chinese)
     *
     * Override the credit line for labels.
     */
    credit_line_for_label_override_zh_hans?: string;
    /**
     * Credit line for label override (Punjabi)
     *
     * Override the credit line for labels.
     */
    credit_line_for_label_override_pa?: string;
    /**
     * Credit line for label override (Hindi)
     *
     * Override the credit line for labels.
     */
    credit_line_for_label_override_hi?: string;
    /**
     * Credit line override (Simplified Chinese)
     *
     * Text that overrides the Work's credit line.
     */
    credit_line_override_zh_hans?: string;
    /**
     * Credit line override (Punjabi)
     *
     * Text that overrides the Work's credit line.
     */
    credit_line_override_pa?: string;
    /**
     * Credit line override (Hindi)
     *
     * Text that overrides the Work's credit line.
     */
    credit_line_override_hi?: string;
};

/**
 * A serializer for Work Images.
 */
export type WorkImageWritable = {
    image_file: string;
    image_file_thumbnail?: string | null;
    image_file_xs?: string | null;
    image_file_s?: string | null;
    image_file_m?: string | null;
    image_file_l?: string | null;
    caption?: string;
    credit_line?: string;
    /**
     * The alternative text for the image. See <a href="https://acmikb.atlassian.net/wiki/spaces/OPS/pages/7964025/" target="_blank">this guide</a> for writing alt text.
     */
    alt_text?: string;
    width?: number | null;
    height?: number | null;
    /**
     * The access level of this object. e.g. No access, onsite or anywhere
     *
     * * `No access` - No access
     * * `View onsite` - View onsite
     * * `View anywhere` - View anywhere
     */
    access_level?: AccessLevelEnum;
};

/**
 * A serializer for Work objects that contains the info needed to represent
 * the work in a constellation, or a tap list.
 */
export type WorkLinkWritable = {
    title: string;
    /**
     * Imported title (Simplified Chinese)
     *
     * The title of the work for the public.
     */
    title_zh_hans?: string;
    /**
     * Imported title (Punjabi)
     *
     * The title of the work for the public.
     */
    title_pa?: string;
    /**
     * Imported title (Hindi)
     *
     * The title of the work for the public.
     */
    title_hi?: string;
    /**
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation?: string;
    /**
     * Title annotation (Simplified Chinese)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_zh_hans?: string;
    /**
     * Title annotation (Punjabi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_pa?: string;
    /**
     * Title annotation (Hindi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_hi?: string;
    /**
     * A url-friendly version of the title
     */
    slug: string;
    credit_line: string;
    /**
     * Imported credit line (Simplified Chinese)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_zh_hans?: string;
    /**
     * Imported credit line (Punjabi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_pa?: string;
    /**
     * Imported credit line (Hindi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_hi?: string;
    record_type?: RecordTypeEnum;
    /**
     * Is this work currently on display in an exhibition?
     */
    is_on_display?: boolean;
    /**
     * The last place this work was on display
     */
    last_on_display_place?: string | null;
    /**
     * The date when this work was last on display
     */
    last_on_display_date?: string | null;
    /**
     * Indigenous context?
     *
     * Checking this will visually decorate the label and online work to indicate an indigenous context.
     */
    is_context_indigenous?: boolean;
    /**
     * A description of the materials used in this work
     */
    material_description?: string;
    /**
     * Unpublish this Work from XOS and the XOS API.
     */
    unpublished?: boolean;
    brief_description: string;
    creator_credit_for_label: string;
    /**
     * Creator credit for label (Simplified Chinese)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_zh_hans?: string;
    /**
     * Creator credit for label (Punjabi)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_pa?: string;
    /**
     * Creator credit for label (Hindi)
     *
     * An alternative creator credit for labels.
     */
    creator_credit_for_label_hi?: string;
    headline_credit_for_label: string;
    /**
     * Headline credit for label (Simplified Chinese)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_zh_hans?: string;
    /**
     * Headline credit for label (Punjabi)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_pa?: string;
    /**
     * Headline credit for label (Hindi)
     *
     * An alternative headline credit for labels.
     */
    headline_credit_for_label_hi?: string;
    /**
     * Imported title for label (Simplified Chinese)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_zh_hans?: string;
    /**
     * Imported title for label (Punjabi)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_pa?: string;
    /**
     * Imported title for label (Hindi)
     *
     * An alternative title of the work for labels.
     */
    title_for_label_hi?: string;
    /**
     * Title for label override (Simplified Chinese)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_zh_hans?: string;
    /**
     * Title for label override (Punjabi)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_pa?: string;
    /**
     * Title for label override (Hindi)
     *
     * Override the imported title of the work for labels.
     */
    title_for_label_override_hi?: string;
    /**
     * Imported description for label (Simplified Chinese)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_zh_hans?: string;
    /**
     * Imported description for label (Punjabi)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_pa?: string;
    /**
     * Imported description for label (Hindi)
     *
     * An alternative description of the work for labels.
     */
    description_for_label_hi?: string;
    /**
     * Description for label override (Simplified Chinese)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_zh_hans?: string;
    /**
     * Description for label override (Punjabi)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_pa?: string;
    /**
     * Description for label override (Hindi)
     *
     * Override the description of the work for labels.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_for_label_override_hi?: string;
    /**
     * Imported description (Simplified Chinese)
     *
     * The brief description of the work for the public.
     */
    description_zh_hans?: string;
    /**
     * Imported description (Punjabi)
     *
     * The brief description of the work for the public.
     */
    description_pa?: string;
    /**
     * Imported description (Hindi)
     *
     * The brief description of the work for the public.
     */
    description_hi?: string;
    /**
     * Description override (Simplified Chinese)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_zh_hans?: string;
    /**
     * Description override (Punjabi)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_pa?: string;
    /**
     * Description override (Hindi)
     *
     * Text that overrides the Work's description. <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> can be used.Use "--" on its own line to indicate a label column break.
     */
    description_override_hi?: string;
};

/**
 * A serializer for Work objects that contains the info needed to represent
 * the work from another work.
 */
export type WorkSubLinkWritable = {
    title: string;
    /**
     * Imported title (Simplified Chinese)
     *
     * The title of the work for the public.
     */
    title_zh_hans?: string;
    /**
     * Imported title (Punjabi)
     *
     * The title of the work for the public.
     */
    title_pa?: string;
    /**
     * Imported title (Hindi)
     *
     * The title of the work for the public.
     */
    title_hi?: string;
    /**
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation?: string;
    /**
     * Title annotation (Simplified Chinese)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_zh_hans?: string;
    /**
     * Title annotation (Punjabi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_pa?: string;
    /**
     * Title annotation (Hindi)
     *
     * An annotation to the title, e.g. "Facsimile"
     */
    title_annotation_hi?: string;
    /**
     * A url-friendly version of the title
     */
    slug: string;
    credit_line: string;
    /**
     * Imported credit line (Simplified Chinese)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_zh_hans?: string;
    /**
     * Imported credit line (Punjabi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_pa?: string;
    /**
     * Imported credit line (Hindi)
     *
     * Text acknowledging the originator of the work and/or its media.
     */
    credit_line_hi?: string;
    record_type?: RecordTypeEnum;
    /**
     * Is this work currently on display in an exhibition?
     */
    is_on_display?: boolean;
    /**
     * The last place this work was on display
     */
    last_on_display_place?: string | null;
    /**
     * The date when this work was last on display
     */
    last_on_display_date?: string | null;
    /**
     * Indigenous context?
     *
     * Checking this will visually decorate the label and online work to indicate an indigenous context.
     */
    is_context_indigenous?: boolean;
    /**
     * A description of the materials used in this work
     */
    material_description?: string;
    /**
     * Unpublish this Work from XOS and the XOS API.
     */
    unpublished?: boolean;
};

export type PlaylistsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this playlist.
         */
        id: number;
    };
    query?: {
        /**
         * Set to false to hide Labels whose Work is not on display.
         */
        not_on_display?: boolean;
        /**
         * Set to false to omit Work thumbnails, e.g. to reduce response time.
         */
        work_thumbnail?: boolean;
    };
    url: '/api/playlists/{id}/';
};

export type PlaylistsRetrieveResponses = {
    200: Playlist;
};

export type PlaylistsRetrieveResponse = PlaylistsRetrieveResponses[keyof PlaylistsRetrieveResponses];

export type WorksRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this Work.
         */
        id: number;
    };
    query?: {
        /**
         * Set to false to omit Work thumbnails, e.g. to reduce response time.
         */
        work_thumbnail?: boolean;
    };
    url: '/api/works/{id}/';
};

export type WorksRetrieveResponses = {
    200: Work;
};

export type WorksRetrieveResponse = WorksRetrieveResponses[keyof WorksRetrieveResponses];
